name: Publish zi-term

on:
  push:
    tags: zi-term-v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-zi-term:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: ./scripts/build
      - name: Run checks
        run: ./scripts/check
      - name: Publish zi-term crate
        run: |
          cd zi-term
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
