name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-zi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./scripts/build
    - name: Run tests
      run: ./scripts/check

  build-zi-crossterm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd backends/crossterm && ../../scripts/build
    - name: Run tests
      run: cd backends/crossterm && ../../scripts/check
